### ISSUE TITLE
Version of Polymer to create component

### ISSUE THREAD

**Issue by caraya** [kappuccino/vimeo-player#3]
I'm trying to decide if this component suits my need but I can't figure out what version of Polymer was used to create it.

**Comment by kappuccino** [comment]
Hello,
Initially writhen 0.5 but @rkstar made an upgrade to 1.0 (https://github.com/rkstar/vimeo-player/commit/b996e2ab3899ab10933070f5130540708e9e4fa9)

**Comment by caraya** [comment]
Thanks.
